repositories:
  ppa: []
  url:
    - "deb https://download.docker.com/linux/ubuntu noble stable"
    - "deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    - "deb https://baltocdn.com/helm/stable/debian/ all main"
    - "deb [arch=arm64] https://apt.releases.hashicorp.com noble main"
    - "deb [arch=arm64] https://packages.microsoft.com/repos/code stable main"
  key:
    - url: "https://download.docker.com/linux/ubuntu/gpg"
    - url: "https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key"
    - url: "https://baltocdn.com/helm/signing.asc"
    - url: "https://apt.releases.hashicorp.com/gpg"
    - url: "https://packages.microsoft.com/keys/microsoft.asc"

remote_executables:
  - name: aws-iam-authenticator
    url: "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.7.1/aws-iam-authenticator_0.7.1_linux_arm64"

shell:
  - curl https://pyenv.run | bash | true
  - curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash | true
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "/tmp/awscliv2.zip" && unzip -u /tmp/awscliv2.zip && sudo ./aws/install --update && rm -rf ./aws
